/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreria_informacion;

import libreria_informacion.Principal_info;
import java.net.URI;

/**
 *
 * @author LENOVO
 */
public class Admi extends javax.swing.JFrame {

    /**
     * Creates new form Admi
     */
    public Admi() {
        initComponents();
    }

    Admi(Principal_info aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atras = new javax.swing.JButton();
        video1 = new javax.swing.JButton();
        video2 = new javax.swing.JButton();
        video3 = new javax.swing.JButton();
        video4 = new javax.swing.JButton();

        atras.setText("Pag.Principal");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        video1.setBackground(new java.awt.Color(204, 102, 255));
        video1.setText("Habilidades Administrativas");
        video1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video1ActionPerformed(evt);
            }
        });

        video2.setBackground(new java.awt.Color(204, 102, 255));
        video2.setText("¿Qué son las habilidades blandas y por qué son cada vez más valoradas?");
        video2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video2ActionPerformed(evt);
            }
        });

        video3.setBackground(new java.awt.Color(204, 102, 255));
        video3.setText("¿Cómo ser más eficaz en tu trabajo?");
        video3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video3ActionPerformed(evt);
            }
        });

        video4.setBackground(new java.awt.Color(204, 102, 255));
        video4.setText("Área de administración de una empresa");
        video4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(video4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(video2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(video3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(video1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atras)
                .addGap(18, 18, 18)
                .addComponent(video1)
                .addGap(32, 32, 32)
                .addComponent(video2)
                .addGap(32, 32, 32)
                .addComponent(video3)
                .addGap(26, 26, 26)
                .addComponent(video4)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
 Principal_info PP = new Principal_info();   
 PP.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void video1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video1ActionPerformed
      if(java.awt.Desktop.isDesktopSupported()){
           java.awt.Desktop desktop= java.awt.Desktop.getDesktop();
           
           if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
               
           try{ 
           java.net.URI uri = new URI("https://youtu.be/YVgtG3WpEpA");
          desktop.browse(uri);
           }catch(Exception e){
               
       }
      }
     }
    }//GEN-LAST:event_video1ActionPerformed

    private void video2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video2ActionPerformed
     if(java.awt.Desktop.isDesktopSupported()){
           java.awt.Desktop desktop= java.awt.Desktop.getDesktop();
           
           if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
               
           try{ 
           java.net.URI uri = new URI("https://youtu.be/51nNGpEO6wg");
          desktop.browse(uri);
           }catch(Exception e){
               
       }
      }
     }
    }//GEN-LAST:event_video2ActionPerformed

    private void video3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video3ActionPerformed
     if(java.awt.Desktop.isDesktopSupported()){
           java.awt.Desktop desktop= java.awt.Desktop.getDesktop();
           
           if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
               
           try{ 
           java.net.URI uri = new URI("https://youtu.be/IZZnnTMRMgs");
          desktop.browse(uri);
           }catch(Exception e){
               
       }
      }
     }
    }//GEN-LAST:event_video3ActionPerformed

    private void video4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video4ActionPerformed
     if(java.awt.Desktop.isDesktopSupported()){
           java.awt.Desktop desktop= java.awt.Desktop.getDesktop();
           
           if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
               
           try{ 
           java.net.URI uri = new URI("https://youtu.be/tVAZ8tYTtgw");
          desktop.browse(uri);
           }catch(Exception e){
               
       }
      }
     }
    }//GEN-LAST:event_video4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton video1;
    private javax.swing.JButton video2;
    private javax.swing.JButton video3;
    private javax.swing.JButton video4;
    // End of variables declaration//GEN-END:variables
}
